### ISSUE TITLE
sigar doesn't compile on FreeBSD 9.1

### ISSUE THREAD

**Issue by pmenglund** [hyperic/sigar#29]
`sigar.c:1071:20: error: utmp.h: No such file or directory`
as `utmp(5)` has been removed in favor for the POSIX `utmpx` (see `getutxent(3)`)

More info in http://lists.freebsd.org/pipermail/freebsd-current/2010-January/014893.html
